### PR TITLE
The Great Formatting

### LINKED ISSUE #5: Proposal: relicense to Apache 2.0
Most http4s projects and otel4s are Apache-2.0.

@ChristopherDavenport and I are the only two contributors as of ff447880c3bdef1c4476da62eb451421f06e0250, so nobody needs to argue about compatibility as long as we both consent.

### PR DESCRIPTION
**Pull request by NthPortal**
Closes #5

### CODE REVIEW

**Comment by NthPortal** [comment]
will `headerCreate` work without a license selected?

and yeah, I can split the commits

**Comment by rossabaker** [comment]
Oh, good point.  headerCreate will work, but it might create the wrong one.  Let me give a nudge.

**Comment by NthPortal** [comment]
apparently the compilation settings got stricter, so I've got something else to fix

**Comment by NthPortal** [comment]
this PR is driving me crazy. I just wanted to format the code, and new things keep failing

**Comment by NthPortal** [comment]
passing build, finally!

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
